<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sjson</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{</string>
	<key>foldingStopMarker</key>
	<string>\}</string>
	<key>name</key>
	<string>sJSON</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#root-object</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.sjson</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>array of values</string>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.sjson</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.array.sjson</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.array.sjson</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\]]</string>
					<key>name</key>
					<string>invalid.illegal.expected-array-separator.sjson</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>comment</key>
			<string>singleline and multiline comment blocks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sjson</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.documentation.sjson</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sjson</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.sjson</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sjson</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.sjson</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>comment</key>
			<string>true/false/null keywords</string>
			<key>match</key>
			<string>\b(?:true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.sjson</string>
		</dict>
		<key>indentifier</key>
		<dict>
			<key>comment</key>
			<string>quotes around object keys are optional if the keys are valid identifiers</string>
			<key>match</key>
			<string>[a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>variable.parameter.meta.structure.key.sjson</string>
		</dict>
		<key>key-value</key>
		<dict>
			<key>comment</key>
			<string>key-value pair</string>
			<key>name</key>
			<string>meta.structure.object.key-value-pair.sjson</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#object-key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(=)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.object.key-value.sjson</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(,)|(?&lt;=[\S&amp;&amp;[^=]])|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.object.pair.sjson</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.structure.object.value.sjson</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#value</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[\S&amp;&amp;[^\}]]</string>
							<key>name</key>
							<string>invalid.illegal.sjson</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[\S&amp;&amp;[^\}]]</string>
					<key>name</key>
					<string>invalid.illegal.sjson</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>comment</key>
			<string>handles integer and decimal numbers</string>
			<key>match</key>
			<string>-?(?:0|[1-9]\d*)(?:(?:\.\d+)?(?:[eE][+-]?\d+)?)?</string>
			<key>name</key>
			<string>constant.numeric.sjson</string>
		</dict>
		<key>object</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.object.begin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>list of key-value pairs</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.object.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.object.sjson</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#key-value</string>
				</dict>
			</array>
		</dict>
		<key>object-key</key>
		<dict>
			<key>comment</key>
			<string>quated string or valid identifier as name</string>
			<key>name</key>
			<string>object-key</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#indentifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-indentifier</string>
				</dict>
			</array>
		</dict>
		<key>root-object</key>
		<dict>
			<key>name</key>
			<string>root-object</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#key-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s+</string>
					<key>name</key>
					<string>spaces</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.sjson</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>string enclosed by double quotes</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.sjson</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.sjson</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})</string>
					<key>name</key>
					<string>constant.character.escape.sjson</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unrecognized-string-escape.sjson</string>
				</dict>
			</array>
		</dict>
		<key>string-indentifier</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.sjson</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>the same as usual string, but with different name</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.sjson</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.meta.structure.key.sjson</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})</string>
					<key>name</key>
					<string>constant.character.escape.sjson</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unrecognized-string-escape.sjson</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sjson</string>
	<key>uuid</key>
	<string>3cf66019-099a-4d2a-9f01-8f91aaabc355</string>
</dict>
</plist>
